<?php
// Establecer el idioma por defecto
$idioma_default = 'es';

// Obtener el idioma de la URL
if (isset($_GET['lang'])) {
    $idioma = $_GET['lang'];
    // Guardar el idioma en una cookie que dura 30 días
    setcookie('idioma', $idioma, time() + (86400 * 30), '/');
}
// Si no hay idioma en la URL, intentar obtenerlo de la cookie
else if (isset($_COOKIE['idioma'])) {
    $idioma = $_COOKIE['idioma'];
}
// Si no hay cookie, usar el idioma por defecto
else {
    $idioma = $idioma_default;
}

// Validar que el idioma sea válido (solo permitir 'es' o 'en')
if (!in_array($idioma, ['es', 'en'])) {
    $idioma = $idioma_default;
}

// Textos en diferentes idiomas
$textos = [
    'es' => [
        'saludo' => 'Hola',
        'cerrar_sesion' => 'Cerrar sesión',
        'actualizar_datos' => 'Actualizar mis datos',
        'realizar_pedidos' => 'Realizar Pedidos',
        'buscar' => 'Buscar productos...',
        'no_productos' => 'No se encontraron productos.',
        'nuestros_productos' => 'Nuestros productos',
        'iniciar_sesion' => 'Iniciar Sesión',
        'registrar' => 'Registrar',
        'registrate' => 'Regístrate',
        'idioma' => 'Idioma',
        'descripcion' => 'Descripción',
        'generos' => 'Géneros',
        'insertar_juego' => 'Insertar Juego',
        'plataformas' => 'Plataformas',
        'titulo' => 'Regístrate',
        'nombre' => 'Nombre',
        'correo' => 'Correo electrónico',
        'telefono' => 'Teléfono',
        'contraseña' => 'Contraseña',
        'confirmar_contraseña' => 'Confirmar contraseña',
        'ya_tienes_cuenta' => '¿Ya tienes una cuenta?',
        'volver' => 'Volver',
        'no_tienes_cuenta' => '¿No tienes una cuenta?',
        'El correo no está registrado' => 'El correo no está registrado',
        'Todos los campos son requeridos' => 'Todos los campos son requeridos',
        'El teléfono no es válido' => 'El teléfono no es válido',
        'Las contraseñas deben de ser iguales' => 'Las contraseñas deben de ser iguales',
        '¡Registro exitoso!' => '¡Registro exitoso!',
        '¡Inicia sesión para empezar a usar tu cuenta!' => '¡Inicia sesión para empezar a usar tu cuenta!',
        'añadir_carrito' => 'Añadir al carrito',
        'añadido_carrito' => 'se añadió al carrito.',
        'error_carrito' => 'Error al añadir el producto al carrito.',
        'problema_carrito' => 'Hubo un problema al añadir el producto al carrito.',
        'precio' => 'Precio',
        'titulo_tienda' => 'Tienda Videojuegos',
        'correo_no_registrado' => 'El correo no está registrado',
        'contraseña_incorrecta' => 'La contraseña es incorrecta',
        'videojuegos_populares' => 'Videojuegos populares',
        'perfil_usuario' => 'Perfil de Usuario',
        'informacion_personal' => 'Información Personal',
        'favoritos' => 'Lista de Favoritos',
        'no_favoritos' => 'No tienes productos en tu lista de favoritos.',
        'resenas' => 'Reseñas',
        'no_resenas' => 'No has realizado reseñas.',
        'acciones_admin' => 'Acciones de Administrador',
        'eliminar_cuenta' => 'Eliminar cuenta',
        'confirmar_eliminar' => '¿Estás seguro de que deseas eliminar tu cuenta? Esta acción no se puede deshacer y perderás todos tus datos, incluyendo el historial de compras, reseñas y favoritos.',
        'actualizar_contraseña' => 'Actualizar Contraseña',
        'actualizar_correo' => 'Actualizar Correo',
        'actualizar_telefono' => 'Actualizar Teléfono',
        'actualizar_nombre' => 'Actualizar Nombre',
        'ver_carrito' => 'Ver carrito',
        'añadir_favorito' => 'Añadir a Favoritos',
        'eliminar_favorito' => 'Eliminar de Favoritos',
        'opciones_admin' => 'Opciones de administración',
        'gestionar_juegos' => 'Gestionar Juegos',
        'editar_juego' => 'Editar juego',
        'eliminar_juego' => 'Eliminar juego',
        'valora_juego' => 'Valora este juego',
        'enviar_valoracion' => 'Enviar valoración',
        'inicia_valorar' => 'Inicia sesión para valorar este juego.',
        'deja_resena' => 'Deja tu reseña',
        'resena' => 'Reseña:',
        'enviar_resena' => 'Enviar reseña',
        'inicia_resena' => 'Inicia sesión para dejar una reseña en este juego.',
        'Valoración_promedio' => 'Valoración promedio',
    ],
    'en' => [
        'saludo' => 'Hello',
        'cerrar_sesion' => 'Log out',
        'actualizar_datos' => 'Update my data',
        'realizar_pedidos' => 'Place Orders',
        'buscar' => 'Search products...',
        'no_productos' => 'No products found.',
        'nuestros_productos' => 'Our products',
        'iniciar_sesion' => 'Log in',
        'registrar' => 'Register',
        'registrate' => 'Register',
        'idioma' => 'Language',
        'descripcion' => 'Description',
        'generos' => 'Genres',
        'insertar_juego' => 'Insert Game',
        'plataformas' => 'Platforms',
        'titulo' => 'Register',
        'nombre' => 'Name',
        'correo' => 'Email',
        'telefono' => 'Phone',
        'contraseña' => 'Password',
        'confirmar_contraseña' => 'Confirm Password',
        'ya_tienes_cuenta' => 'Already have an account?',
        'volver' => 'Back',
        'no_tienes_cuenta' => 'Don\'t have an account?',
        'El correo no está registrado' => 'The email is not registered',
        'Todos los campos son requeridos' => 'All fields are required',
        'El teléfono no es válido' => 'The phone number is not valid',
        'Las contraseñas deben de ser iguales' => 'The passwords must be the same',
        '¡Registro exitoso!' => 'Registration successful!',
        '¡Inicia sesión para empezar a usar tu cuenta!' => 'Log in to start using your account!',
        'añadir_carrito' => 'Add to cart',
        'añadido_carrito' => 'was added to the cart.',
        'error_carrito' => 'Error adding the product to the cart.',
        'problema_carrito' => 'There was a problem adding the product to the cart.',
        'precio' => 'Price',
        'titulo_tienda' => 'Game Store',
        'correo_no_registrado' => 'The email is not registered',
        'contraseña_incorrecta' => 'The password is incorrect',
        'videojuegos_populares' => 'Popular Video Games',
        'perfil_usuario' => 'User Profile',
        'informacion_personal' => 'Personal Information',
        'favoritos' => 'Favorites List',
        'no_favoritos' => 'You have no products in your favorites list.',
        'resenas' => 'Reviews',
        'no_resenas' => 'You have not written any reviews.',
        'acciones_admin' => 'Admin Actions',
        'eliminar_cuenta' => 'Delete account',
        'confirmar_eliminar' => 'Are you sure you want to delete your account? This action cannot be undone and you will lose all your data, including purchase history, reviews, and favorites.',
        'actualizar_contraseña' => 'Update Password',
        'actualizar_correo' => 'Update Email',
        'actualizar_telefono' => 'Update Phone',
        'actualizar_nombre' => 'Update Name',
        'ver_carrito' => 'View cart',
        'añadir_favorito' => 'Add to Favorites',
        'eliminar_favorito' => 'Remove from Favorites',
        'opciones_admin' => 'Admin options',
        'gestionar_juegos' => 'Manage Games',
        'editar_juego' => 'Edit game',
        'eliminar_juego' => 'Delete game',
        'valora_juego' => 'Rate this game',
        'enviar_valoracion' => 'Send rating',
        'inicia_valorar' => 'Log in to rate this game.',
        'deja_resena' => 'Leave your review',
        'resena' => 'Review:',
        'enviar_resena' => 'Send review',
        'inicia_resena' => 'Log in to leave a review for this game.',
        'Valoración_promedio' => 'Average rating',
    ],
];
?>